version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    runtime-versions:
      java: openjdk8
      android: 28
      # name: version
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    # - 'app/build/outputs/apk/dev/debug/app-dev-debug.apk'
    - '**/*'
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
